networks:
  app-tier:
    driver: bridge

services:
  app:
    container_name: app
    
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - app-tier
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Add workspace as current working directory 
    volumes:
      - ..:/workspace:cached
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  kafka:
    container_name: kafka

    image: bitnami/kafka
    networks:
      - app-tier
    # Add workspace as current working directory 
    volumes:
      - ..:/workspace:cached

    # Provide environment for kafka to run Kraft 
    environment:
      # Kraft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    # Add "forwardPorts" to **devcontainer.json** to forward Kafka locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
